import assert from 'node:assert/strict';
import { execFileSync, spawnSync } from 'node:child_process';
import { mkdtempSync, rmSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { test } from 'node:test';
import { fileURLToPath } from 'node:url';
import { openTerminal } from './support/terminal.ts';

test('the local candidate runs its own Node and native SQLite from a Unicode path with an empty PATH', async (t) => {
  const root = mkdtempSync(join(tmpdir(), 'Boardroom package '));
  t.after(() => rmSync(root, { recursive: true, force: true }));
  const candidate = join(root, 'paquet François avec espaces');
  const packager = fileURLToPath(new URL('../scripts/package.mjs', import.meta.url));
  const built = spawnSync(process.execPath, [packager, '--output', candidate], { encoding: 'utf8' });
  assert.equal(built.status, 0, built.stderr);
  const runtime = join(candidate, 'runtime', process.platform === 'win32' ? 'node.exe' : 'node');
  const cli = join(candidate, 'dist', 'cli.js');
  const data = join(root, 'durable data é');
  const env = { ...process.env, PATH: '', NODE_PATH: '', NODE_OPTIONS: '' };
  const run = (...args: string[]) => execFileSync(runtime, [cli, ...args, '--data-dir', data], { encoding: 'utf8', cwd: root, env });
  assert.match(run('demo', '--next'), /Product Owner/);
  assert.match(run('demo', '--next'), /Lead Developer/);
  assert.match(run('evidence'), /Team: two engineers/);
  const exported = JSON.parse(run('export', '--output', join(root, 'output'), '--json'));
  assert.match(readFileSync(exported.plan, 'utf8'), /Recorded example/);
  const history = JSON.parse(run('history', '--json'));
  assert.equal(history.events[0].type, 'recorded.message');
  assert.equal(history.events[1].type, 'recorded.message');
  assert.equal(history.operations[0].id, exported.operationId);
  assert.equal(history.operations[0].status, 'completed');
  assert.equal(history.operations[0].receipts.length, 2);
  const diagnostics = JSON.parse(run('doctor', '--json'));
  assert.equal(diagnostics.checkpointReopen, 'verified');
  assert.deepEqual(diagnostics.pdfDocx, { pdf: 'verified', docx: 'verified' });
  const pdf = JSON.parse(run('document', '--source', join(candidate, 'assets', 'validation', 'launch.pdf'), '--allow-source', '--json'));
  const docx = JSON.parse(run('document', '--source', join(candidate, 'assets', 'validation', 'launch.docx'), '--allow-source', '--json'));
  assert.equal(JSON.parse(run('evidence', '--id', pdf.evidence.id, '--page', '2', '--json')).text, 'Launch scope: one integration.');
  assert.equal(JSON.parse(run('evidence', '--id', docx.evidence.id, '--block', '2', '--json')).text, 'Budget: €500 for the café pilot.');
  assert.match(run('demo', '--terminal'), /INSUFFICIENT_EVIDENCE/);
  const beforeTerminal = JSON.parse(run('history', '--json'));
  const terminal = openTerminal(t, [cli, 'terminal-check', '--data-dir', data], { executable: runtime, cwd: root, env });
  await terminal.waitFor(/Stream tick: [1-9]/);
  terminal.write('\x1b[200~Capacity:\r\ncafé 😀\x1b[201~');
  await terminal.waitFor(/Draft: Capacity:\ncafé 😀/);
  terminal.resize(44, 18);
  await terminal.waitFor(/Window: 44x18/);
  terminal.write('\r');
  terminal.resize(100, 30);
  await terminal.waitFor(/Accepted: "Capacity:\\ncafé 😀"/);
  terminal.write('\x1b');
  assert.equal((await terminal.finish()).exitCode, 130);
  assert.deepEqual(JSON.parse(run('history', '--json')), beforeTerminal);
  const manifest = JSON.parse(readFileSync(join(candidate, 'manifest.json'), 'utf8'));
  assert.equal(manifest.runtime, process.version);
  assert.equal(manifest.platform, process.platform);
  assert.match(readFileSync(join(candidate, 'README.md'), 'utf8'), /Try the local example/);
  assert.match(readFileSync(join(candidate, 'docs', 'architecture.md'), 'utf8'), /Public boundaries/);
});
